--CREACION DE PK

ALTER TABLE CLIENTES
    ADD CONSTRAINT Clientes_PK PRIMARY KEY (idCliente);
    
ALTER TABLE PAGO
    ADD CONSTRAINT Pagos_PK PRIMARY KEY (idPago);
    
ALTER TABLE FACTURA
    ADD CONSTRAINT Facturas_PK PRIMARY KEY (iDFactura);
    
ALTER TABLE CONTRATOS
    ADD CONSTRAINT Contratos_PK PRIMARY KEY (numeroContrato);
    
ALTER TABLE RESERVAS
    ADD CONSTRAINT Reservas_PK PRIMARY KEY (idRESERVAS);
    
ALTER TABLE SERVICIO
    ADD CONSTRAINT Servicios_PK PRIMARY KEY (idServicio);
    
ALTER TABLE MOBILIARIO
    ADD CONSTRAINT Moviliarios_PK PRIMARY KEY (idMobiliario);
    
ALTER TABLE USUARIOS
    ADD CONSTRAINT Usuarios_PK PRIMARY KEY (idUsuarios);

ALTER TABLE ESPACIO
    ADD CONSTRAINT Espacios_PK PRIMARY KEY (idEspacio);
    
ALTER TABLE SISTEMA
    ADD CONSTRAINT Sistema_PK PRIMARY KEY (SISTEMA_ID);