--CREACION DE TABLAS 

--TABLA CLIENTES
create table CLIENTES(
idCliente INTEGER  NOT NULL,
cedula VARCHAR2(10)NOT NULL,
nombres VARCHAR2(50) NOT NULL,
apellidos VARCHAR2(50)NOT NULL,
ciudad VARCHAR2(50)NOT NULL,
telefono VARCHAR2(10)NOT NULL,
direccion VARCHAR2(100) NOT NULL
);

--TABLA SERVICIO
create table SERVICIO(
idServicio INTEGER NOT NULL,
tipoServicio VARCHAR2(50)NOT NULL,
nombreServicio VARCHAR2(50) NOT NULL,
valorServicio NUMBER NOT NULL,
RESERVAS_idReservas INTEGER NOT NULL
);

--TABLA FACTURA
create table FACTURA(
iDFactura INTEGER NOT NULL,
fechaFactura DATE NOT NULL
);

--TABLA CONTRATOS
create table CONTRATOS(
numeroContrato INTEGER NOT NULL,
CLIENTES_idCliente INTEGER NOT NULL,
SERVICIO_idServicio INTEGER NOT NULL,
FACTURA_idFactura INTEGER NOT NULL
);

--TABLA PAGO
create table PAGO(
idPago INTEGER NOT NULL,
tipoPago VARCHAR2(50)NOT NULL,
fechaPago DATE NOT NULL,
precio NUMBER NOT NULL,
FACTURA_idFactura INTEGER NOT NULL
);

--TABLA RESERVAS
create table RESERVAS(
idRESERVAS INTEGER NOT NULL,
fechaReserva Date NOT NULL,
fechaFinReserva DATE NOT NULL,
CLIENTES_idCliente INTEGER,
CONTRATOS_numeroContrato INTEGER NOT NULL
);

--TABLA MOBILIARIO
create table MOBILIARIO(
idMobiliario INTEGER NOT NULL,
tipoMobiliario VARCHAR2(50) NOT NULL,
nombreMobiliario VARCHAR2(50),
precioMobiliario NUMBER NOT NULL,
USUARIOS_idUsuario INTEGER NOT NULL,
 SERVICIO_idServicio INTEGER NOT NULL
);

--TABLA ESPACIO
create table ESPACIO(
idEspacio INTEGER NOT NULL,
tipoEspacio VARCHAR2(50)NOT NULL,
nombreEspacio VARCHAR2(50) NOT NULL,
cantidadEspacio INTEGER NOT NULL,
precioEspacio NUMBER NOT NULL,
USUARIOS_idUsuario INTEGER,
SERVICIO_idServicio INTEGER
);

--TABLA USUARIOS 
create table USUARIOS(
idUsuarios INTEGER NOT NULL,
tipoUsuario VARCHAR2(50) NOT NULL,
nombreUsuario VARCHAR2(50) NOT NULL,
clave VARCHAR2(50) NOT NULL,
funcion VARCHAR2(50) NOT NULL,
USUARIOS_idUsuario INTEGER,
 SISTEMA_SISTEMA_ID NUMBER
);

--TABLA SISTEMA
create table SISTEMA(
SISTEMA_ID NUMBER NOT NULL
);