ALTER TABLE CLIENTES
    DROP CONSTRAINT Clientes_PK;
    
ALTER TABLE PAGO
    DROP CONSTRAINT Pagos_PK;
    
ALTER TABLE FACTURA
    DROP CONSTRAINT Facturas_PK;
    
ALTER TABLE CONTRATOS
    DROP CONSTRAINT Contratos_PK;
    
ALTER TABLE RESERVAS
    DROP CONSTRAINT Reservas_PK;
    
ALTER TABLE SERVICIO
    DROP CONSTRAINT Servicios_PK;
    
ALTER TABLE MOBILIARIO
    DROP CONSTRAINT Moviliarios_PK;
    
ALTER TABLE USUARIOS
    DROP CONSTRAINT Usuarios_PK;
    
ALTER TABLE ESPACIO
    DROP CONSTRAINT Espacios_PK;
    
ALTER TABLE SISTEMA
    DROP CONSTRAINT Sistema_PK;