--ELIMINAR TABLA CLIENTES
DROP TABLE CLIENTES;

--ELIMINAR TABLA CONTRATOS
DROP TABLE CONTRATOS;

--ELIMINAR TABLA ESPACIO
DROP TABLE ESPACIO;

--ELIMINAR TABLA FACTURA
DROP TABLE FACTURA;

--ELIMINAR TABLA MOBILIARIO
DROP TABLE MOBILIARIO;

--ELIMINAR TABLA PAGO
DROP TABLE PAGO;

--ELIMINAR TABLA RESERVAS
DROP TABLE RESERVAS;

--ELIMINAR TABLA DE SERVICIOS
DROP TABLE SERVICIO;

--ELIMINAR TABLA DE SISTEMA
DROP TABLE SISTEMA;

--ELIMINAR TABLA DE USUARIOS
DROP TABLE USUARIOS;

